"""inicial

Revision ID: 0eeb061b87a3
Revises: 
Create Date: 2026-07-01 21:49:21.008122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eeb061b87a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactos',
    sa.Column('ContactoId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=200), nullable=False),
    sa.Column('Email', sa.String(length=200), nullable=False),
    sa.Column('Mensaje', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('ContactoId')
    )
    op.create_table('usuarios',
    sa.Column('UsuarioId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NombreUsuario', sa.String(length=100), nullable=False),
    sa.Column('Contrasena', sa.String(length=255), nullable=False),
    sa.Column('TipoUsuario', sa.Enum('Admin', 'Cajero', name='tipo_usuario'), nullable=False),
    sa.PrimaryKeyConstraint('UsuarioId'),
    sa.UniqueConstraint('NombreUsuario')
    )
    op.create_table('clientes',
    sa.Column('ClienteId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=200), nullable=False),
    sa.Column('Email', sa.String(length=200), nullable=False),
    sa.Column('ContactoId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ContactoId'], ['contactos.ContactoId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ClienteId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    op.drop_table('usuarios')
    op.drop_table('contactos')
    # ### end Alembic commands ###